def run(**args):
    raise RuntimeError("Raising run time error in 'test_exception_in_run'")